sonar.projectKey=portfolioadvanced-llm
sonar.organization=yerbis09
sonar.projectName=Portfolio Advanced LLM
sonar.projectVersion=0.1.0

sonar.sources=pubsub_archetype
sonar.exclusions=pubsub_archetype/tests/**,**/__pycache__/**,**/.venv/**,**/uv.lock

sonar.tests=pubsub_archetype/tests
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
